# Generated by Django 4.2.6 on 2023-10-21 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("search", "0001_initial"),
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="searchitems",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searchItems",
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="searchitems",
            name="search",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searchItems",
                to="search.searchlog",
            ),
        ),
        migrations.AddField(
            model_name="gptchat",
            name="user_chat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gptChat",
                to="search.userchat",
            ),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatitems",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatItems",
                to="search.userchat",
            ),
        ),
        migrations.AddField(
            model_name="chatitems",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatItems",
                to="items.item",
            ),
        ),
    ]
