# Generated by Django 4.2.6 on 2023-10-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="first_query",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
