# Generated by Django 4.2.6 on 2023-10-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_rename_brand_item_brand_id_and_more"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptchat",
            name="items",
            field=models.ManyToManyField(to="items.item"),
        ),
        migrations.AddField(
            model_name="searchlog",
            name="items",
            field=models.ManyToManyField(to="items.item"),
        ),
        migrations.DeleteModel(
            name="ItemPageviewLog",
        ),
    ]
