# Generated by Django 4.2.6 on 2023-10-14 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_gptchat_items_searchlog_items_delete_itempageviewlog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatlog",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="gptchat",
            old_name="log_id",
            new_name="log",
        ),
        migrations.RenameField(
            model_name="searchlog",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="userchat",
            old_name="log_id",
            new_name="log",
        ),
    ]
