# Generated by Django 4.2.6 on 2023-11-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatlog",
            old_name="first_query",
            new_name="summary",
        ),
        migrations.AddField(
            model_name="searchlog",
            name="gpt_query1",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="searchlog",
            name="gpt_query2",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="searchlog",
            name="gpt_query3",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
