# Generated by Django 4.2.6 on 2023-11-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_rename_first_query_chatlog_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gptchat",
            name="gpt_query1",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gptchat",
            name="gpt_query2",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gptchat",
            name="gpt_query3",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
