# Generated by Django 4.2.6 on 2023-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0003_rename_user_id_chatlog_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
