# Generated by Django 4.2.6 on 2023-10-14 11:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="brand",
            new_name="brand_id",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="category",
            new_name="category_id",
        ),
        migrations.AddField(
            model_name="item",
            name="color",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="feature_vector",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("U", "Unisex")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="material",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="order_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
