# Generated by Django 4.2.6 on 2023-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="feature_vector",
        ),
        migrations.AlterField(
            model_name="category",
            name="relation",
            field=models.ManyToManyField(
                related_name="+", through="items.CategoryHierarchy", to="items.category"
            ),
        ),
    ]
