# Generated by Django 4.2.6 on 2023-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="order_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
