# Generated by Django 4.2.6 on 2023-10-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_remove_item_feature_vector_alter_category_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="relation",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="items.category",
            ),
        ),
        migrations.DeleteModel(
            name="CategoryHierarchy",
        ),
    ]
