# Generated by Django 4.2.6 on 2023-10-14 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_rename_brand_item_brand_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="brand_id",
            new_name="brand",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="category_id",
            new_name="category",
        ),
    ]
