# Generated by Django 4.2.6 on 2023-10-21 10:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_remove_category_relation_category_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image_url",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=512),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
