# Generated by Django 4.2.6 on 2023-10-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_alter_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
